In [ ]:
import pandas as pd

df_csv=pd.read_csv("/content/USA_Housing.csv")
df_csv

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df_xls=pd.read_excel("/shiptoid.xlsx")
df_xls

    ShiptoID  LONGTITUDE   LATITUDE
0     3001BR  151.001259 -33.797556
1     3002BR  149.206300 -35.347000
2     3003BR  147.343011 -35.122016
3     3004BR  150.850020 -33.760995
4     3005BR  153.129468 -30.287126
..       ...         ...        ...
481   9005BR  130.841039 -12.447294
482   9006BR  130.855646 -12.401724
483   9008BR  130.869043 -12.428968
484   9010BR  130.929297 -12.436861
485   9012BR  130.929297 -12.436861

[486 rows x 3 columns]

In [ ]:
df_csv.shape

(5000, 7)

In [ ]:
df_xls.shape

(486, 3)

In [ ]:
df_csv.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [ ]:
df_xls.isnull().sum()

ShiptoID      0
LONGTITUDE    0
LATITUDE      0
dtype: int64

In [ ]:
df_csv.isnull().values.any()

np.False_

In [ ]:
df_csv.dtypes

Avg. Area Income                float64
Avg. Area House Age             float64
Avg. Area Number of Rooms       float64
Avg. Area Number of Bedrooms    float64
Area Population                 float64
Price                           float64
Address                          object
dtype: object

In [ ]:
df_xls.dtypes

ShiptoID       object
LONGTITUDE    float64
LATITUDE      float64
dtype: object

In [ ]:
(df_csv==0).sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [ ]:
(df_xls==0).sum()

ShiptoID      0
LONGTITUDE    0
LATITUDE      0
dtype: int64

In [ ]:
df_xls.sort_values(by="LATITUDE",ascending=True)

    ShiptoID  LONGTITUDE   LATITUDE
473   8017BR  147.315508 -42.973031
471   8010BR  147.315508 -42.973031
472   8015BR  147.315508 -42.973031
466   8001BR  147.318828 -42.879204
474   8019BR  147.289587 -42.841069
..       ...         ...        ...
478   9001BR  130.929297 -12.436861
485   9012BR  130.929297 -12.436861
484   9010BR  130.929297 -12.436861
483   9008BR  130.869043 -12.428968
482   9006BR  130.855646 -12.401724

[486 rows x 3 columns]

In [ ]:
df_csv.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [ ]:
student_data={
  'Stud_id':[1,2,3,4,5],
  'Name':["a","b","c","d","e"],
  'Age':[10,23,45,65,12],
  'Gender':['M','F','M','M','F'],
  'Dept':["CS","IT","Mech","ENTC","CIVIL"],
  'Marks':[30,56,78,23,'NaN'],
  'Attedance':["Present","Absent","Present","Absent","Present"],
  "Intern":[True,False,True,False,True]
}
df_student=pd.DataFrame(student_data)
df_student

   Stud_id Name  Age Gender   Dept Marks Attedance  Intern
0        1    a   10      M     CS    30   Present    True
1        2    b   23      F     IT    56    Absent   False
2        3    c   45      M   Mech    78   Present    True
3        4    d   65      M   ENTC    23    Absent   False
4        5    e   12      F  CIVIL   NaN   Present    True

In [ ]:
c=avg=0
for student in df_student['Marks']:
  if student!='NaN':
    c=c+1
    avg=avg+student
avg=avg/c

df_student=df_student.replace(to_replace="NaN",value=avg)
df_student

/tmp/ipython-input-3313124542.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_student=df_student.replace(to_replace="NaN",value=avg)

   Stud_id Name  Age Gender   Dept  Marks Attedance  Intern
0        1    a   10      M     CS  30.00   Present    True
1        2    b   23      F     IT  56.00    Absent   False
2        3    c   45      M   Mech  78.00   Present    True
3        4    d   65      M   ENTC  23.00    Absent   False
4        5    e   12      F  CIVIL  46.75   Present    True

In [ ]:
#finding mode in marks and replace it
median_student=df_student['Marks'].median()
print(median_student)

43.0

In [ ]:
df_student=df_student.replace(to_replace="NaN",value=median_student)
df_student

/tmp/ipython-input-3842640201.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_student=df_student.replace(to_replace="NaN",value=median_student)

   Stud_id Name  Age Gender   Dept  Marks Attedance  Intern
0        1    a   10      M     CS   30.0   Present    True
1        2    b   23      F     IT   56.0    Absent   False
2        3    c   45      M   Mech   78.0   Present    True
3        4    d   65      M   ENTC   23.0    Absent   False
4        5    e   12      F  CIVIL   43.0   Present    True

In [ ]:
top_students=df_student[df_student['Marks']>50].copy()
top_students

   Stud_id Name  Age Gender  Dept  Marks Attedance  Intern
1        2    b   23      F    IT   56.0    Absent   False
2        3    c   45      M  Mech   78.0   Present    True

In [ ]:
pd.merge(df_student,top_students)

   Stud_id Name  Age Gender  Dept  Marks Attedance  Intern
0        2    b   23      F    IT   56.0    Absent   False
1        3    c   45      M  Mech   78.0   Present    True